### ISSUE TITLE
TS2497

### ISSUE THREAD

**Issue by monolithed** [akim-mcmath/deep-map#9]
```ts
import * as deepMap from 'deep-map';
```

```
error TS2497: Module '"/node_modules/deep-map/lib/index"' resolves to a non-module entity and cannot be imported using this construct.
```

**Comment by mcmath** [comment]
Hi,

I need to update the declarations for Typescript 2.x. I'll do so shortly.

**Comment by mcmath** [comment]
Actually, if the "module" compiler option is "CommonJS" (the default), you can do this:

```ts
import deepMap = require('deep-map');
```

I will update this so it works with ES2015 modules too.

**Comment by monolithed** [comment]
@mcmath, I know (

**Comment by mcmath** [comment]
I've released a new version as `v1.5.0`. You can now import the function as a default import:

```ts
import deepMap from 'deep-map';
```

Thanks for raising this issue.

**Comment by monolithed** [comment]
@mcmath, thanks, but could you tell about sense of adding the tslib dependency?

**Comment by mcmath** [comment]
@monolithed: TypeScript normally adds helpers to the files it emits. With [tslib][1], it imports them instead, so you only have one copy of each helper instead of one per file. This is preferable for libraries, since it can reduce file size quite a bit. It's like [babel-runtime][2] for TypeScript projects.

[1]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#support-for-external-helpers-library-tslib
[2]: https://babeljs.io/docs/plugins/transform-runtime/
